version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: BookCatalog.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  blazor:
    build:
      context: .
      dockerfile: BookCatalog.Frontend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - API_BASE_ADDRESS=http://localhost:5000

networks:
  app-network:
    driver: bridge