version: "3.9"
services:
  api:
    build:
      context: ./BookCatalog.API
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose API on localhost:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  blazor:
    build:
      context: ./BookCatalog.Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose Blazor app on localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
