version: "3.9"
services:
  api:
    build:
      context: ./BookCatalog.API
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose container's port 5000 on host's port 5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  blazor:
    build:
      context: ./BookCatalog.Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
      - API_BASE_ADDRESS=http://localhost:5000


networks:
  app-network:
    driver: bridge
